[package]
name = "advent_of_rust"
version = "1.0.0"
authors = ["drademacher <danny.rademacher@gmail.com>"]
edition = "2021"
publish = false


[dependencies]
md-5 = "0.10.6"
regex = "1.10.3"
serde_json = "1.0.114"
