name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        name: CI
        steps:
            - uses: actions/checkout@v3
            - name: Change directory to year 2015
              run: cd 2015
            - name: cargo test
              run: cargo test
            # - name: cargo clippy
            #   run: cargo clippy -- -D warnings
            - name: cargo fmt
              run: cargo fmt --check
