name: Display all AoC ⭐
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
        matrix:
          year: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
    steps:
      - uses: actions/checkout@v4

      - name: Put stars for specific
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_USERID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: ${{ matrix.year }}
          tableMarker: <!--- advent_readme_stars table 2015 --->
          headerPrefix: "###"

      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars
